repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation "androidx.media3:media3-transformer:1.11.0"
    implementation "androidx.media3:media3-effect:1.11.0"
    implementation "androidx.media3:media3-common:1.11.0"
}

android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
